apiVersion: v1
kind: Pod
metadata:
  name: ansible-runner
  namespace: default
spec:
  containers:
    - image: ansible/ansible-runner
      name: ansible-runner
      tty: true
      stdin: true
      imagePullPolicy: Always
      args:
        - sleep
        - infinity

