kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: regulatory-admin
subjects:
- kind: Group
  name: devops@gogotech.hk
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: regulator
  apiGroup: rbac.authorization.k8s.io
